### ISSUE TITLE
App crashing on startup

### ISSUE THREAD

**Issue by jeetdholakia** [Hessam-Emami/MovieDb#1]
Hi there,

The app crashes on startup with the following error 

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.emami.moviedb/com.emami.moviedb.app.ui.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property fragmentFactory has not been initialized
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property fragmentFactory has not been initialized
        at com.emami.moviedb.app.ui.MainActivity.onCreate(MainActivity.kt:16)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)`

Please let me know how to sort this out. 

Thanks

**Comment by Hessam-Emami** [comment]
Thanks a lot for submitting this issue,
The crash was caused due to how Dagger Hilt operates and is now fixed.

**Comment by jeetdholakia** [comment]
Thanks alot @Hessam-Emami
